language: vim

os:
  - linux
  - osx

before_script:
  - if [[ "$TRAVIS_OS_NAME" == linux ]]; then sudo apt-get -qq update && sudo apt-get install -y vim-gtk; fi
  - if [[ "$TRAVIS_OS_NAME" == osx ]]; then brew update && brew install vim; fi

script:
    - test/run
